### PR TITLE
Update main.py

### PR DESCRIPTION
**Pull request by GravuTrad**
To correct language fault.

### CODE REVIEW

**Comment by SilicaAndPina** [comment]
What language Fault?

**Comment by CelesteBlue-dev** [comment]
grr manager not mannnnnnnnager

**Comment by SilicaAndPina** [comment]
OOH i wrote "Mannager" not "Manager" 
Xd lol yep can do ill update that everywhere i made the mistake

right?

**Comment by CelesteBlue-dev** [comment]
Update all in once.

**Pull request closed without merging**
